name: 12-hour-cron
on:
  schedule:
    - cron: "* */12 * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request POST \
          --url 'https://fee-alerts.bucko.vercel.com/api/fees' \
          --header 'Authorization: Bearer ${{ secrets.FEES_API_KEY}}'
