name: Check mempool state
on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call /api/fees to trigger check
        shell: bash
        env:
          API_ORIGIN: ${{ secrets.API_ORIGIN }}
          FEES_API_KEY: ${{ secrets.FEES_API_KEY}}
        run: |
          curl --request GET \
          --url "$API_ORIGIN/api/fees" \
          --header "Authorization: $FEES_API_KEY"
